### ISSUE TITLE
Thank You Qwerty Space

### ISSUE THREAD

**Issue by KOHISTORIAN** [Qwerty-Space/Discord-Spam-Script#12]
When I first used this I had no troubles, worked perfectly well and levelled up my pokemon by 60 levels, (also upped my Mee6 level ;3) but sadly the next day I couldn’t run it for more than a minute without getting interrupted by Mee6...is there a way to slow down the script? 

5* Would Recommend @Qwerty-Space 

Edit: I’m using Hotkey

**Comment by Qwerty-Space** [comment]
Yup. There's two ways to slow it down, the timer in between messages, and the timer in between loops. It should be commented, so open up the script in your text editor (notepad++, sublime, VSCode) and change those values

**Comment by KOHISTORIAN** [comment]
Much Appreciated! My laptop lags at times so it builds up the default emoji message meaning it comes out with like 20 at once! I managed to find an alternative way to slow it down, but will go into the script if I need to in the end :3
