### ISSUE TITLE
smiley

### ISSUE THREAD

**Issue by bueluke** [Qwerty-Space/Discord-Spam-Script#2]
how do i change the smiley to something else

**Comment by bueluke** [comment]
msg me on discord Captain Luke #0069 AND TELL ME HOW TO CHANGE THE SMILEY TO A TEXT

**Comment by Qwerty-Space** [comment]
[Here](https://github.com/Qwerty-Space/Discord-Spam-Script/blob/eaf1ff036a02a81ba28eb60c3080ea361587a70d/Discord-Spam-Script.ahk#L19).

Read the readme file.
