### ISSUE TITLE
How can i change the language of script?

### ISSUE THREAD

**Issue by Citarn** [Qwerty-Space/Discord-Spam-Script#3]
I am trying to make it Turkish Keyboard.
And how can i ping someone with that script?
It doesn't works with @X#XXXX.

**Comment by Qwerty-Space** [comment]
Can you show me your code?

**Comment by Citarn** [comment]
https://user-images.githubusercontent.com/42324306/44039692-46845ca0-9f22-11e8-91c0-097e42b3b320.PNG

**Comment by Qwerty-Space** [comment]
Try `SendInput @Gvidas#1`
